version: '3'
services:
  web:
    image: "php:7.2-apache"
    volumes:
    - "./:/var/www/html"
    - "./php-conf:/usr/local/etc/php/conf.d:ro"
    ports:
    - "80:80"
    - "443:443"
  mail:
    image: "mailhog/mailhog"
    ports:
    - "8025:8025"
